CREATE TABLE IF NOT EXISTS kcc_iss."Account_Details"
(
    "ApplicationId" character varying(17) COLLATE pg_catalog."default" NOT NULL,
    "accountNumber" character varying(20) COLLATE pg_catalog."default",
    "branchCode" character varying(6) COLLATE pg_catalog."default",
    ifsc character varying(11) COLLATE pg_catalog."default",
    "accountHolder" numeric
);


CREATE TABLE IF NOT EXISTS kcc_iss."Basic_Details"
(
    "ApplicationId" character varying(17) COLLATE pg_catalog."default" NOT NULL,
    "beneficiaryName" character varying(60) COLLATE pg_catalog."default",
    "aadhaarNumber" character varying(12) COLLATE pg_catalog."default",
    "beneficiaryPassbookName" character varying(60) COLLATE pg_catalog."default",
    mobile character varying(10) COLLATE pg_catalog."default",
    dob character varying(10) COLLATE pg_catalog."default",
    gender numeric,
    "socialCategory" numeric,
    "farmerCategory" numeric,
    "farmerType" numeric,
    "primaryOccupation" numeric,
    "relativeType" numeric,
    "relativeName" character varying(60) COLLATE pg_catalog."default",
    residential_vill text COLLATE pg_catalog."default",
    pincode character varying(6) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    cif_no character varying(17) COLLATE pg_catalog."default",
    CONSTRAINT "Basic_Details_pkey" PRIMARY KEY ("ApplicationId")
);


CREATE TABLE IF NOT EXISTS kcc_iss."Batch_Processed_2022_2023"
(
    "Id" integer NOT NULL DEFAULT nextval('kcc_iss."Batch_Processed_2021_2022_Id_seq"'::regclass),
    "ApplicationId" character varying(19) COLLATE pg_catalog."default" NOT NULL,
    "BatchAckId" character varying(22) COLLATE pg_catalog."default",
    "ProcessedDate" date,
    "Status" character varying(20) COLLATE pg_catalog."default",
    "uniqueId" character varying(19) COLLATE pg_catalog."default",
    "isDeleted" character varying(3) COLLATE pg_catalog."default",
    error character varying(750) COLLATE pg_catalog."default",
    "farmerId" character varying(20) COLLATE pg_catalog."default",
    "LoanAppplicationNumber" character varying(20) COLLATE pg_catalog."default",
    to_be_deleted text COLLATE pg_catalog."default",
    "deleteBatchAckId" text COLLATE pg_catalog."default",
    delete_error text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS kcc_iss."KCCCropDetailExisting_2022_2023"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "KCCExistingLandId" integer NOT NULL,
    "AccountNo" text COLLATE pg_catalog."default",
    "Season" text COLLATE pg_catalog."default",
    "Crop" text COLLATE pg_catalog."default",
    "IrrigatedArea" numeric NOT NULL,
    "UnIrrigatedArea" numeric NOT NULL,
    "SOFIrrigatedArea" numeric NOT NULL,
    "SOFUnIrrigatedArea" numeric NOT NULL,
    "CropInsurance" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_KCCCropDetailExisting4" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS kcc_iss."KCCExistingLand_2022_2023"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "AccountNo" text COLLATE pg_catalog."default",
    "District" text COLLATE pg_catalog."default",
    "Tehsil" text COLLATE pg_catalog."default",
    "RI" text COLLATE pg_catalog."default",
    "Village" text COLLATE pg_catalog."default",
    "OwnerName" text COLLATE pg_catalog."default",
    "DharanAdhikar" text COLLATE pg_catalog."default",
    "RajaswaNyayalay" text COLLATE pg_catalog."default",
    "OtherInfo" text COLLATE pg_catalog."default",
    "SourceofIrrigation" text COLLATE pg_catalog."default",
    "KhasraNo" text COLLATE pg_catalog."default",
    "Charge" text COLLATE pg_catalog."default",
    "TotalArea" numeric NOT NULL,
    "IrrigatedArea" numeric NOT NULL,
    "UnIrrigatedArea" numeric NOT NULL,
    "NonAgriArea" numeric NOT NULL,
    "DistrictCode" text COLLATE pg_catalog."default",
    "TehsilCode" text COLLATE pg_catalog."default",
    "VillageCode" text COLLATE pg_catalog."default",
    "LandKhata" text COLLATE pg_catalog."default",
    "fbDistrictCode" text COLLATE pg_catalog."default",
    "fbTehsilCode" text COLLATE pg_catalog."default",
    "fbVillageCode" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_KCCExistingLand4" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS kcc_iss."KCC_ISS_ACTIVITY_2022_2023"
(
    "ApplicationId" character varying(17) COLLATE pg_catalog."default",
    "ActivityType" numeric,
    "liveStockType" numeric,
    "liveStockCode" numeric,
    "unitCount" numeric,
    "inlandType" numeric,
    "totalUnits" numeric,
    "totalArea" numeric
);

CREATE TABLE IF NOT EXISTS kcc_iss."KCC_ISS_CLAIM_BATCH_PROCESSED_2022_2023"
(
    "Id" integer NOT NULL DEFAULT nextval('loanflow."KCC_ISS_CLAIM_BATCH_PROCESSED_2022_23_Id_seq"'::regclass),
    "LoanAppplicationNumber" character varying(19) COLLATE pg_catalog."default" NOT NULL,
    "BatchAckId" character varying(22) COLLATE pg_catalog."default",
    "ClaimDate" date,
    "ClaimAmount" numeric,
    "Status" character varying(20) COLLATE pg_catalog."default",
    "uniqueId" character varying(19) COLLATE pg_catalog."default",
    "isDeleted" character varying(3) COLLATE pg_catalog."default",
    error character varying(750) COLLATE pg_catalog."default",
    "claimNumber" text COLLATE pg_catalog."default",
    delete_error text COLLATE pg_catalog."default",
    "deleteBatchAckId" text COLLATE pg_catalog."default",
    "isClosed" text COLLATE pg_catalog."default",
    claim_type text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS kcc_iss."Loan_Details_2022_2023"
(
    "ApplicationId" integer NOT NULL DEFAULT nextval('kcc_iss."Loan_Details_2022_2023_ApplicationId_seq"'::regclass),
    "kccLoanSanctionedDate" date,
    "kccLoanSanctionedAmount" numeric,
    "kccDrawingLimitforFY" numeric
);


CREATE TABLE IF NOT EXISTS kcc_iss.crop_mapping
(
    season text COLLATE pg_catalog."default",
    crop text COLLATE pg_catalog."default",
    crop_code text COLLATE pg_catalog."default"
);


CREATE TABLE IF NOT EXISTS kcc_iss.crop_master
(
    "cropCode" character varying(20) COLLATE pg_catalog."default",
    "cropName" character varying(100) COLLATE pg_catalog."default",
    "categoryCode" numeric,
    "categoryName" character varying(100) COLLATE pg_catalog."default"
);


CREATE TABLE IF NOT EXISTS kcc_iss.district_master_lvl
(
    dist_code text COLLATE pg_catalog."default",
    dist_name text COLLATE pg_catalog."default",
    lvl4 text COLLATE pg_catalog."default",
    lvl4code text COLLATE pg_catalog."default",
    lvl4name text COLLATE pg_catalog."default",
    lvl7 text COLLATE pg_catalog."default",
    lvl7code text COLLATE pg_catalog."default",
    lvl7name text COLLATE pg_catalog."default"
);



CREATE TABLE IF NOT EXISTS kcc_iss.kcc_iss_claim_2022_2023
(
    "ApplicationId" character varying(17) COLLATE pg_catalog."default",
    "loanSanctionedDate" date,
    "loanRepaymentDate" date,
    "sanctionedAmount" numeric,
    "totalDebit" numeric,
    "totalISClaim" numeric,
    "totalPRIClaim" numeric,
    bank_iss_claim numeric,
    bank_pri_claim numeric,
    pen_is_claim numeric
);


CREATE TABLE IF NOT EXISTS kcc_iss.kcc_master_branch
(
    "branchCode" character varying(6) COLLATE pg_catalog."default",
    "branchName" character varying(150) COLLATE pg_catalog."default",
    "ifscCode" character varying(11) COLLATE pg_catalog."default"
);




